server:
  port: 8003

spring:
  application:
    name:cloud-hystrix-producer-service

eureka;
  client:
    reigster-with-eureka: true
    fetch-register: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka